### ISSUE TITLE
[CRITICAL] Flutter releases_$platform.json format has changed

### ISSUE THREAD

**Issue by kuhnroyal** [leoafarias/fvm#106]
The format of the https://storage.googleapis.com/flutter_infra/releases/releases_macos.json suddenly changed and now all CI builds fail. This is not a bug but it requires an update.

The JSON no longer has a `channels` map but `current_release` with the hash of the release.
```
{
  "base_url": "https://storage.googleapis.com/flutter_infra/releases",
  "current_release": {
    "beta": "bbfbf1770cca2da7c82e887e4e4af910034800b6",
    "dev": "7c6f9dd2396dfe7deb6fd11edc12c10786490083",
    "stable": "bbfbf1770cca2da7c82e887e4e4af910034800b6"
  },
  "releases": [
    {
      "hash": "bbfbf1770cca2da7c82e887e4e4af910034800b6",
      "channel": "beta",
      "version": "1.20.2",
      "release_date": "2020-08-14T20:58:13.245691Z",
      "archive": "beta/macos/flutter_macos_1.20.2-beta.zip",
      "sha256": "3f6fe6fecf7d91b6d78a3d64cd2c577f7d4202e03f38cdac584462a438918b38"
    },
    ...
}
```

**To Reproduce**
1. Run any command that parses version from the storage `fvm install/use x.x.x` 

```
$ fvm install 1.20.2
Unhandled exception:
NoSuchMethodError: Class '_CastError' has no instance getter 'message'.
Receiver: Instance of '_CastError'
Tried calling: message
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      fvmRunner.<anonymous closure> (package:fvm/fvm.dart:30:45)
#2      _RootZone.runBinary (dart:async/zone.dart:1455:54)
#3      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#6      Future._completeError (dart:async/future_impl.dart:537:5)
#7      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#8      CommandRunner.runCommand (package:args/command_runner.dart)
<asynchronous suspension>
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#10     new Future.sync (dart:async/future.dart:223:31)
#11     CommandRunner.run (package:args/command_runner.dart:112:14)
#12     fvmRunner (package:fvm/fvm.dart:26:23)
#13     main (file:///Users/p.leibiger/.pub-cache/hosted/pub.intern.sk/fvm-1.1.7/bin/main.dart:4:9)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

This needs to be handled in `fvm.dart` - errors that are not exceptions don't have a message field.

After some debugging I got to the root cause:
```
Unhandled exception:
type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      new Channels.fromMap (package:fvm/flutter/flutter_releases.dart:109:44)
#1      new FlutterReleases.fromMap (package:fvm/flutter/flutter_releases.dart:68:26)
#2      releasesFromMap (package:fvm/flutter/flutter_releases.dart:51:21)
#3      getReleases (package:fvm/flutter/flutter_releases.dart:27:24)
<asynchronous suspension>
#4      inferFlutterVersion (package:fvm/flutter/flutter_helpers.dart:11:26)
#5      InstallCommand.run (package:fvm/commands/install.dart:48:34)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#8      new Future.sync (dart:async/future.dart:223:31)
#9      CommandRunner.run (package:args/command_runner.dart:112:14)
#10     fvmRunner (package:fvm/fvm.dart:26:23)
#11     main (file:///Users/p.leibiger/.pub-cache/hosted/pub.intern.sk/fvm-1.1.7/bin/main.dart:4:9)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by leoafarias** [comment]
@kuhnroyal thanks for this I pushed the fix on master, and on pub version 1.1.8

**Comment by leoafarias** [comment]
The payload did not change. I created a hashmap of the currentReleases to compare. However since hash repeats between channels only one entry is added to the hashmap. 

Before FVM used git to get tags and determine if its a valid flutter version. Now it uses the releases payload. I will look into this further later to see how this can be optimized this is fixed.

**Comment by leoafarias** [comment]
Did another small change version 1.1.9. Will have to write more tests for this piece of fvm. I am not really using this piece except to compare versions but it will be important on some items in the future.

**Comment by kuhnroyal** [comment]
Thanks for the quick reaction!
