### ISSUE TITLE
[BUG] 'pub' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kentcb** [leoafarias/fvm#123]
**Describe the bug**
First time I've tried `fvm`, but pretty sure this isn't supposed to happen:

```
❯ fvm use 1.22.0-1.0.pre
Project now uses Flutter: 1.22.0-1.0.pre
Unhandled exception:
Exception: Sorry could not link C:\Users\Kent\fvm\versions\1.22.0-1.0.pre
#0      createLink (package:fvm/utils/helpers.dart:43:5)
#1      updateFlutterSdkBinLink (package:fvm/utils/project_config.dart:29:3)
#2      setAsProjectVersion (package:fvm/utils/project_config.dart:23:3)
#3      UseCommand.run (package:fvm/commands/use.dart:77:7)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#6      new Future.sync (dart:async/future.dart:223:31)
#7      CommandRunner.run (package:args/command_runner.dart:112:14)
#8      fvmRunner (package:fvm/fvm.dart:27:23)
#9      main (file:///C:/Users/Kent/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
'pub' is not recognized as an internal or external command,
operable program or batch file.
```

**To Reproduce**
1. `fvm install 1.22.0-1.0.pre`
2. `cd a_flutter_project`
3. `fvm use 1.22.0-1.0.pre`

**Expected behavior**
`fvm use` should work as advertised.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - FVM `1.2.3`

**Comment by leoafarias** [comment]
@kentcb could you provide which version of dart you are running?

**Comment by toshiossada** [comment]
same error 


```
λ fvm use stable --global
The global Flutter version is now stable
Make sure sure to add C:\Users\Avell\fvm\default\bin to your PATH environment variable
Unhandled exception:
Exception: Sorry could not link C:\Users\Avell\fvm\versions\stable
#0      createLink (package:fvm/utils/helpers.dart:43:5)
#1      setAsGlobalVersion (package:fvm/flutter/flutter_tools.dart:145:3)
#2      UseCommand.run (package:fvm/commands/use.dart:74:7)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:223:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      fvmRunner (package:fvm/fvm.dart:27:23)
#8      main (file:///C:/Users/Avell/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/fvm-1.2.3/bin/main.dart:4:9)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by leoafarias** [comment]
@toshiossada Could you send me the logs when you sun with the `--verbose` flag?

**Comment by toshiossada** [comment]
I solved runing as administrato

**Comment by leoafarias** [comment]
@kentcb Could you confirm that running as an administrator solves it for you?

**Comment by leoafarias** [comment]
Will be closing this issue as part of a better documentation guide for running on windows on #119
