### ISSUE TITLE
Directory listing failed

### ISSUE THREAD

**Issue by FranPitri** [leoafarias/fvm#13]
Hey mate. First things first, great package!

I've been using fvm for some time now and it's been great. However, I installed v0.0.4 from pub today, and tried to run `fvm list`. Unfortunately, it ran into some errors.

Here's the output:

```
▶ fvm list --verbose
[     0.019s] Oops, something went wrong: Directory listing failed
[     0.027s]
Unhandled exception:
type '_StackTrace' is not a subtype of type 'String'
#0      fvmRunner.<anonymous closure> (package:fvm/fvm.dart:39:23)
#1      _RootZone.runBinary (dart:async/zone.dart:1384:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#5      Future._completeError (dart:async/future_impl.dart:530:5)
#6      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#7      CommandRunner.runCommand (package:args/command_runner.dart)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     fvmRunner (package:fvm/fvm.dart:33:23)
<asynchronous suspension>
#12     main (file:///home/pitri/.pub-cache/hosted/pub.dartlang.org/fvm-0.0.4/bin/main.dart:4:9)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Any ideas on what could be wrong?

**Comment by leoafarias** [comment]
Good to hear @FranPitri. This version is under heavy development has I have rewritten from Go to Dart. This issue happens because there are no current flutter sdks installed through fvm. I have updated version 0.0.5. You still get the same error, but I will review that to make sure there are better error messages.

Also I have updated Readme.md to reflect some of the updates
