### ISSUE TITLE
[BUG] [1.3.8-Windows 10] Strange install/use behaviour dependent on the hard drive

### ISSUE THREAD

**Issue by JSBmanD** [leoafarias/fvm#254]
**Describe the bug**
Nor install nor use is working on latest package version from pub

**To Reproduce**
1. Windows 10 (Developer mode enabled)
2. Open command prompt as administrator
3. Run `fvm install 2.0.3`
4. It installs flutter
5. Go to project folder (another drive)
6. Run `fvm use 2.0.3` or `fvm install 2.0.3`
7. Check...
8. See error

**Expected behavior**
Install or use of fvm.

**Logs**
```
C:\Windows\system32>fvm install 2.0.3
Flutter 2.0.3 • channel unknown • unknown source
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

D:\>cd Projects/proj

D:\Projects\proj>fvm install
Could not install <2.0.3>
#0      installWorkflow (package:fvm/src/workflows/install_version.workflow.dart:44:5)
<asynchronous suspension>
#1      InstallCommand.run (package:fvm/src/commands/install_command.dart:45:7)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#3      FvmCommandRunner.run (package:fvm/src/runner.dart:60:14)
<asynchronous suspension>
#4      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-1.3.8/bin/main.dart:4:3)
<asynchronous suspension>



D:\Projects\proj>fvm use 2.0.3 --verbose
[     0.272s] Exception: On Windows FVM requires to run in developer mode or as an administrator
Could not install <2.0.3>
#0      installWorkflow (package:fvm/src/workflows/install_version.workflow.dart:44:5)
<asynchronous suspension>
#1      useVersionWorkflow (package:fvm/src/workflows/use_version.workflow.dart:25:3)
<asynchronous suspension>
#2      UseCommand.run (package:fvm/src/commands/use_command.dart:53:5)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#4      FvmCommandRunner.run (package:fvm/src/runner.dart:60:14)
<asynchronous suspension>
#5      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-1.3.8/bin/main.dart:4:3)
<asynchronous suspension>
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - FVM Version 1.3.8
 - If Windows: default PS or default command prompt in admin mode

**Comment by leoafarias** [comment]
@JSBmanD The error happens when the symlink cannot be created. Can you run `fvm install --verbose`, I want to see if we have the trace of the error.

**Comment by JSBmanD** [comment]
@leoafarias
```
C:\Windows\system32>fvm install 2.0.3 --verbose
[     0.203s] Version: 2.0.3 - already installed.
Flutter 2.0.3 • channel unknown • unknown source
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
D:\Projects\proj>fvm install 2.0.3 --verbose
[     0.253s] Exception: On Windows FVM requires to run in developer mode or as an administrator
Could not install <2.0.3>
#0      installWorkflow (package:fvm/src/workflows/install_version.workflow.dart:44:5)
<asynchronous suspension>
#1      InstallCommand.run (package:fvm/src/commands/install_command.dart:50:7)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#3      FvmCommandRunner.run (package:fvm/src/runner.dart:60:14)
<asynchronous suspension>
#4      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-1.3.8/bin/main.dart:4:3)
<asynchronous suspension>
```

**Comment by leoafarias** [comment]
@JSBmanD can you install version `2.0.0-dev.4`

`pub global activate fvm 2.0.0-dev.4`

and run the `fvm install --verbose` command again.

**Comment by JSBmanD** [comment]
@leoafarias 
```
C:\Windows\system32>fvm install 2.0.3 --verbose
[     0.662s] Version: 2.0.3 - already installed.
fvm: running version "2.0.3"

Flutter 2.0.3 • channel unknown • unknown source
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
----------------------------------------- then I change the drive
D:\Projects\proj>fvm install 2.0.3 --verbose
[     0.339s] Version: 2.0.3 - already installed.
fvm: running version "2.0.3"

Flutter 2.0.3 • channel unknown • unknown source
Framework • revision 4d7946a68d (2 weeks ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

D:\Projects\proj>fvm use 2.0.3 --verbose
[     0.284s] Version: 2.0.3 - already installed.
[     0.294s] Cannot create link to target 'C:\Users\User\fvm\versions\2.0.3'
Internal Error: On Windows FVM requires to run in developer mode or as an administrator
Unhandled exception:
Exception: Could not save config changes
#0      ConfigService.save (package:fvm/src/services/config_service.dart:44:7)
<asynchronous suspension>
#1      ProjectService.pinVersion (package:fvm/src/services/project_service.dart:88:5)
<asynchronous suspension>
#2      useVersionWorkflow (package:fvm/src/workflows/use_version.workflow.dart:28:3)
<asynchronous suspension>
#3      UseCommand.run (package:fvm/src/commands/use_command.dart:95:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#5      FvmCommandRunner.run (package:fvm/src/runner.dart:70:24)
<asynchronous suspension>
#6      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-2.0.0-dev.4/bin/main.dart:6:8)
<asynchronous suspension>
[     0.267s] Version: 2.0.3 - already installed.
[     0.277s] Cannot create link to target 'C:\Users\User\fvm\versions\2.0.3'
Internal Error: On Windows FVM requires to run in developer mode or as an administrator
Unhandled exception:
Exception: Could not save config changes
#0      ConfigService.save (package:fvm/src/services/config_service.dart:44:7)
<asynchronous suspension>
#1      ProjectService.pinVersion (package:fvm/src/services/project_service.dart:88:5)
<asynchronous suspension>
#2      useVersionWorkflow (package:fvm/src/workflows/use_version.workflow.dart:28:3)
<asynchronous suspension>
#3      UseCommand.run (package:fvm/src/commands/use_command.dart:95:5)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#5      FvmCommandRunner.run (package:fvm/src/runner.dart:70:24)
<asynchronous suspension>
#6      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/fvm-2.0.0-dev.4/bin/main.dart:6:8)
<asynchronous suspension>
```

**Comment by leoafarias** [comment]
@JSBmanD Thanks for that. I went ahead and created a separate partition on my windows machine and ran it. The only way I could replicate this error message is if my user did not have WRITE access to the drive the project was in.

My versions are stored on C:// and my project was on D://

If I did not have write permissions for the drive I receive the exact same error. 

To get it to run successfully
- User need to have write access to D://
- PowerShell needs to run on Admin mode.

**Comment by JSBmanD** [comment]
@leoafarias I already have write permission for all users to write on that drive. Moreover I'll test it now with full access applied. Can you specify with which command in terminal I can run fvm from sources? (sorry for the stupid question I'm usually working just with flutter)

**Comment by JSBmanD** [comment]
@leoafarias after modifying permissions I have one more log:
```
PS D:\Projects\proj> dart pub --trace global run 'fvm:main' use '2.0.3'
The getter 'source' was called on null.
Receiver: null
Tried calling: source
dart:core                                                        Object.noSuchMethod
package:pub/src/global_packages.dart 353:34                      GlobalPackages.find
package:pub/src/command/global_run.dart 69:44                    GlobalRunCommand.runProtected
dart:async                                                       new Future.sync
package:pub/src/utils.dart 113:12                                captureErrors.wrappedCallback
dart:async                                                       runZonedGuarded
package:pub/src/utils.dart 130:5                                 captureErrors
package:pub/src/command.dart 164:13                              PubCommand.run
package:args/command_runner.dart 196:27                          CommandRunner.runCommand
package:dartdev/dartdev.dart 199:30                              DartdevRunner.runCommand
package:args/command_runner.dart 112:25                          CommandRunner.run.<fn>
dart:async                                                       new Future.sync
package:args/command_runner.dart 112:14                          CommandRunner.run
package:dartdev/dartdev.dart 53:29                               runDartdev
C:\b\s\w\ir\cache\builder\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. Please run

    dart pub --trace pub --trace global run 'fvm:main' use '2.0.3'
```

**Comment by leoafarias** [comment]
@JSBmanD Can you add the log for `fvm use 2.0.3` This log seems to be coming from Dart even before hitting fvm.

**Comment by JSBmanD** [comment]
@leoafarias it was dart problem (I've installed it from **chocolatery**) and when I removed it and downloaded zip - fvm started to work in project. Maybe it should be as troubleshooting thing in readme for future.

**Comment by leoafarias** [comment]
Do you think tweaking the message would help a bit as far as having permissions?

**Comment by JSBmanD** [comment]
@leoafarias maybe you can reference this issue in P.S. after that error message.

**Comment by leoafarias** [comment]
I will go ahead and improve this message. For now will close this.
