### ISSUE TITLE
Create package error: Guards.canExecute (package:fvm/src/utils/guards.dart:15:7)

### ISSUE THREAD

**Issue by tazik561** [leoafarias/fvm#292]
I am trying to create package by fvm like this:

`fvm flutter create --template=package my_project
`
I got this error :
```
$ fvm flutter create --template=package my_project


Cannot execute 

#0      Guards.canExecute (package:fvm/src/utils/guards.dart:15:7)
<asynchronous suspension>
#1      _runCmd (package:fvm/src/utils/commands.dart:88:3)
<asynchronous suspension>
#2      flutterGlobalCmd (package:fvm/src/utils/commands.dart:76:10)
<asynchronous suspension>
#3      FlutterCommand.run (package:fvm/src/commands/flutter_command.dart:39:14)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:196:13)
<asynchronous suspension>
#5      FvmCommandRunner.run (package:fvm/src/runner.dart:73:24)
<asynchronous suspension>
#6      main (file:///home/Alt/.pub-cache/hosted/pub.dartlang.org/fvm-2.0.4/bin/main.dart:6:8)
<asynchronous suspension>
```

This is my FVM version:
```
$ fvm --version
2.0.4
```
SDK list: 

```
$ fvm list
Cache Directory:  /home/Alt/fvm/versions

stable
1.27.0-4.0.pre
1.22.6
```
and doctor
```
$ fvm doctor

No FVM config found:
/mnt/SSDP/Project/AltProjects/plugins
Fvm will run the version in your PATH env: null

Configured env paths:
___________________________________________________

Flutter:


Dart:
/usr/lib/dart/bin/dart

```

**Comment by leoafarias** [comment]
@tazik561 it seems there is no version configured for global or for the path, so there is no fallback.

Go ahead and do “fvm global stable” and try the command again.

**Comment by leoafarias** [comment]
@tazik561 it seems there is no version configured for global or for the path, so there is no fallback.

Go ahead and do “fvm global stable” and try the command again.

**Comment by leoafarias** [comment]
Closing this, please  reopen if this does not solve your provlem

**Comment by tazik561** [comment]
> Closing this, please reopen if this does not solve your provlem

Sorry for late, I run `fvm global stable` 

```
Alt@MxAlt:~
$ fvm global stable
Flutter "stable" has been set as global
However your "flutter" path current points to:

.
to use global Flutter SDK through FVM you should change it to:

/home/Alt/fvm/default/bin
Alt@MxAlt:~
```
So after that I again run doctor:
```
$ fvm doctor

No FVM config found:
/home/Alt
Fvm will run the version in your PATH env: null

Configured env paths:
___________________________________________________

Flutter:


Dart:
/usr/lib/dart/bin/dart

Alt@MxAlt:~
```

I still got `No FVM config found:` .

**Comment by leoafarias** [comment]
That means there is no config in the path. You are probably not running the command within a flutter project.

Also you haven't set the flutter app as described in the instructions.
