### ISSUE TITLE
I have a problem installing all flutter versions and channels 

### ISSUE THREAD

**Issue by techwithsam** [leoafarias/fvm#329]
I have a problem installing all flutter version and channel including changing settings, while installation process done correctly 
```
Internal Error: could not save FVM settings
```
![Screenshot 2021-06-23 090222](https://user-images.githubusercontent.com/42917957/123059767-02630900-d402-11eb-92cc-050f3aaa656b.png)

**Comment by leoafarias** [comment]
@techwithsam moved it here since this is not a sidekick issue. Can you confirm that  the `C:\Users\samue\fvm\.settings` exist in that folder, even if does not it should not give an error, I am not sure what is going on, any further other info you can provide?

**Comment by techwithsam** [comment]
There is no folder just a file
![Screenshot 2021-06-24 021427](https://user-images.githubusercontent.com/42917957/123187369-f0c94200-d491-11eb-9565-40108a04cfc9.png)

**Comment by techwithsam** [comment]
> @techwithsam moved it here since this is not a sidekick issue. Can you confirm that the `C:\Users\samue\fvm\.settings` exists in that folder, even if does not it should not give an error, I am not sure what is going on, any further other info you can provide?

Okay

**Comment by leoafarias** [comment]
@techwithsam not sure how this file got there, can you remove it. Install fvm again make sure you are running 2.2.2, and do the install to see if that resolves the issue

**Comment by techwithsam** [comment]
**Still the same**

**Installation** 
```
PS C:\WINDOWS\system32> choco install fvm
Chocolatey v0.10.15
Installing the following packages:
fvm
By installing you accept licenses for the packages.
Progress: Downloading fvm 2.2.2... 100%

fvm v2.2.2 [Approved]
fvm package files install completed. Performing other installation steps.
The package fvm wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): yes

Fetching Dart dependencies...
Building executable...
Info: Compiling with sound null safety
Generated: c:\programdata\chocolatey\lib\fvm\bin\fvm.exe
Added C:\ProgramData\chocolatey\bin\fvm.exe shim pointed to '..\lib\fvm\bin\fvm.exe'.
 ShimGen has successfully created a shim for fvm.exe
 The install of fvm was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
```

**Installing Flutter version**
```
PS C:\WINDOWS\system32> fvm install 2.2.2
Flutter "2.2.2" is not installed.

Installing version: 2.2.2...

Could not install 2.2.2

Please run command with  --verbose if you want more information

PS C:\WINDOWS\system32> fvm install 2.2.2 --verbose
[     0.004s] FileSystemException: Cannot open file, path = 'C:\Users\samue\fvm\.settings' (OS Error: The system cannot find the file specified.
, errno = 2)
[     0.008s] FileSystemException: Cannot open file, path = 'C:\Users\samue\fvm\.settings' (OS Error: The system cannot find the file specified.
, errno = 2)
[     0.010s] FileSystemException: Cannot open file, path = 'C:\Users\samue\fvm\.settings' (OS Error: The system cannot find the file specified.
, errno = 2)
2.2.2 exists but was not setup correctly. Doing cleanup...
[     0.015s] FileSystemException: Cannot open file, path = 'C:\Users\samue\fvm\.settings' (OS Error: The system cannot find the file specified.
, errno = 2)
[     0.018s] FileSystemException: Cannot open file, path = 'C:\Users\samue\fvm\.settings' (OS Error: The system cannot find the file specified.
, errno = 2)
Flutter "2.2.2" is not installed.

Installing version: 2.2.2...
[     0.028s] FileSystemException: Cannot open file, path = 'C:\Users\samue\fvm\.settings' (OS Error: The system cannot find the file specified.
, errno = 2)
[     0.051s] SocketException: Failed host lookup: 'raw.githubusercontent.com' (OS Error: No such host is known.
, errno = 11001)
[     0.055s] Internal Error: Failed to retrieve the Flutter SDK from: https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json
Fvm will use the value set on env FLUTTER_STORAGE_BASE_URL to check versions
if you are located in China, please see this page: https://flutter.dev/community/china

Could not install 2.2.2

Please run command with  --verbose if you want more information

```

**Comment by mreichelt** [comment]
I don't know if this is the same issue, but I can install all recent Flutter versions but 2.2.2.
Installing 2.2.1 works, but this is the output for 2.2.2:

```console
$ fvm install 2.2.2 --verbose
Internal Error: Could not infer Flutter Version 2.2.2
#0      inferFlutterVersion (package:fvm/src/flutter_tools/flutter_helpers.dart:27:5)
<asynchronous suspension>
#1      InstallCommand.run (package:fvm/src/commands/install_command.dart:50:23)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#4      new Future.sync (dart:async/future.dart:223:31)
#5      CommandRunner.run (package:args/command_runner.dart:112:14)
#6      fvmRunner (package:fvm/src/runner.dart:35:18)
#7      main (file:///Users/mreichelt/.pub-cache/hosted/pub.dartlang.org/fvm-1.3.7/bin/main.dart:6:9)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Unhandled exception:
Internal Error: Could not infer Flutter Version 2.2.2
#0      inferFlutterVersion (package:fvm/src/flutter_tools/flutter_helpers.dart:27:5)
<asynchronous suspension>
#1      InstallCommand.run (package:fvm/src/commands/install_command.dart:50:23)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#3      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#4      new Future.sync (dart:async/future.dart:223:31)
#5      CommandRunner.run (package:args/command_runner.dart:112:14)
#6      fvmRunner (package:fvm/src/runner.dart:35:18)
#7      main (file:///Users/mreichelt/.pub-cache/hosted/pub.dartlang.org/fvm-1.3.7/bin/main.dart:6:9)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```


More infos:

```console
$ fvm version
1.3.7

$ flutter --version
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (5 months ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

**Comment by mreichelt** [comment]
Ok, I could fix it for me. The problem was that I was using an old version of fvm (1.3.7 instead of 2.2.2), which I installed according to the fvm docs using `dart pub global activate fvm`. But because I was using Flutter SDK 1.22.6 (needed for a project) to install FVM that could only pick the old FVM version.

I had to uninstall FVM using `pub global deactivate fvm`, and install it using `brew install fvm` instead to get the latest version - then `fvm install 2.2.2` worked fine.

But **warning**: Installing this via Homebrew installed me *another* Dart SDK via Homebrew, which my `PATH` variable picked up. So now I had conflicting versions of Dart (newer) and Flutter (older).
To fix this I changed my `.profile` file from:

`export PATH=$PATH:~/bin/flutter/bin:~/bin/flutter/bin/cache/dart-sdk/bin`

to:

`export PATH=~/bin/flutter/bin:~/bin/flutter/bin/cache/dart-sdk/bin:$PATH`


@techwithsam I saw that you already use FVM 2.2.2, so your problem seems to be different from mine.

**Comment by techwithsam** [comment]
Hi @leoafarias, I have resolved the issue I just follow the @mreichelt process and everything works fine

**Steps I took**
1. Run PowerShell as administrator 
2. Run `pub global deactivate fvm`
3. Run `dart pub global activate fvm`
4. `fvm list`
5. Run `fvm install <flutter SDK version>` e.g 2.2.2 and that's it, issue resolved.

Thanks, @mreichelt & @leoafarias

**Comment by techwithsam** [comment]
closing issue now
