### ISSUE TITLE
[BUG] fvm throws type 'Null' is not a subtype of type 'String' after installing new version.

### ISSUE THREAD

**Issue by petroczizoltan** [leoafarias/fvm#802]
**Before creating a bug report please make check the following**

- [x] You have read our [FAQ](https://fvm.app/docs/guides/faq)
- [x] If you have used flutter. Please install correctly, run `pub cache repair`. Close the terminal and try again.
- [ ] If you are on Windows. Make sure you are running the terminal as `administrator` or with `developer` permissions.
- [x] Run `fvm doctor` if possible and add the output to the issue.

**Describe the bug**
I added version 3.22.3 and installed it later.

<details> <summary> `fvm global 3.22.3` output </summary>

```
Flutter SDK: SDK Version : 3.22.3 is not installed.
✔ Would you like to install it now? · yes                                                                                         
✓ Flutter SDK: SDK Version : 3.22.3 installed! (2.3s)
Unhandled exception:
type 'Null' is not a subtype of type 'String'
#0      new ExternalHostedReference.fromJson (package:pubspec/src/dependency.dart:138)
#1      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:25)
#2      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:107)
#3      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113)
#4      MapBase.forEach (dart:collection/maps.dart:35)
#5      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112)
#6      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:107)
#7      new PubSpec.fromYamlString (package:pubspec/src/pubspec.dart:120)
#8      Project.loadFromPath (package:fvm/src/models/project_model.dart:82)
#9      ProjectService.findAncestor (package:fvm/src/services/project_service.dart:42)
#10     GlobalCommand.run (package:fvm/src/commands/global_command.dart:86)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#12     FvmCommandRunner.runCommand (package:fvm/src/runner.dart:245)
<asynchronous suspension>
#13     FvmCommandRunner.run (package:fvm/src/runner.dart:124)
<asynchronous suspension>
#14     Scope.run (package:scope/src/scope.dart:151)
<asynchronous suspension>
#15     main (file:///private/tmp/fvm-20241202-89186-j6089r/fvm-3.2.1/bin/main.dart:13)
<asynchronous suspension>
```

</details>

<details> <summary> Before installing </summary>

```json
{
  "size": "8.08 GB",
  "versions": [
    {
      "name": "3.22.3",
      "directory": "/Users/zoltanpetroczi/fvm/versions/3.22.3",
      "releaseFromChannel": null,
      "type": "release",
      "binPath": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin",
      "hasOldBinPath": false,
      "dartBinPath": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin",
      "dartExec": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin/dart",
      "flutterExec": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin/flutter",
      "flutterSdkVersion": null,
      "dartSdkVersion": null,
      "isSetup": false
    }
  ]
}
```

</details>

<details>
<summary> After installing </summary>

```json
{
  "size": "8.34 GB",
  "versions": [
    {
      "name": "3.22.3",
      "directory": "/Users/zoltanpetroczi/fvm/versions/3.22.3",
      "releaseFromChannel": null,
      "type": "release",
      "binPath": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin",
      "hasOldBinPath": false,
      "dartBinPath": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin",
      "dartExec": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin/dart",
      "flutterExec": "/Users/zoltanpetroczi/fvm/versions/3.22.3/bin/flutter",
      "flutterSdkVersion": "3.22.3",
      "dartSdkVersion": "3.4.4",
      "isSetup": true
    }
  ]
}
```

</details>

<details>
<summary> `fvm doctor` output </summary>

```
Unhandled exception:
type 'Null' is not a subtype of type 'String'
#0      new ExternalHostedReference.fromJson (package:pubspec/src/dependency.dart:138)
#1      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:25)
#2      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:107)
#3      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113)
#4      MapBase.forEach (dart:collection/maps.dart:35)
#5      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112)
#6      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:107)
#7      new PubSpec.fromYamlString (package:pubspec/src/pubspec.dart:120)
#8      Project.loadFromPath (package:fvm/src/models/project_model.dart:82)
#9      ProjectService.findAncestor (package:fvm/src/services/project_service.dart:42)
#10     DoctorCommand.run (package:fvm/src/commands/doctor_command.dart:205)
#11     CommandRunner.runCommand (package:args/command_runner.dart:212)
#12     CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:89)
#13     FvmCommandRunner.runCommand (package:fvm/src/runner.dart:245)
#14     FvmCommandRunner.run (package:fvm/src/runner.dart:124)
#15     main.<anonymous closure> (file:///private/tmp/fvm-20241202-89186-j6089r/fvm-3.2.1/bin/main.dart:13)
#16     _rootRun (dart:async/zone.dart:1399)
#17     _CustomZone.run (dart:async/zone.dart:1301)
#18     _runZoned (dart:async/zone.dart:1804)
#19     runZoned (dart:async/zone.dart:1747)
#20     Scope.run (package:scope/src/scope.dart:151)
#21     main (file:///private/tmp/fvm-20241202-89186-j6089r/fvm-3.2.1/bin/main.dart:13)
#22     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
#23     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

</details>

**To Reproduce**

1. Go to terminal..
2. Run `fvm global version`...
3. Run almost any fvm command. (eg: `fvm doctor` or `fvm list`)

**Expected behavior**
No error thrown and command output shown correctly

**Logs**
Please provide the verbose logs by running `--verbose` after the command.
<details> <summary> `fvm list --verbose` </summary>

```
fvm list --verbose

Argument information:
  Top level options:
  - verbose: true

Command: list

Cache directory:  /Users/zoltanpetroczi/fvm/versions
Directory Size: 8.54 GB

Searching for project in *project directory*
Unhandled exception:
type 'Null' is not a subtype of type 'String'
#0      new ExternalHostedReference.fromJson (package:pubspec/src/dependency.dart:138)
#1      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:25)
#2      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:107)
#3      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113)
#4      MapBase.forEach (dart:collection/maps.dart:35)
#5      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112)
#6      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:107)
#7      new PubSpec.fromYamlString (package:pubspec/src/pubspec.dart:120)
#8      Project.loadFromPath (package:fvm/src/models/project_model.dart:82)
#9      ProjectService.findAncestor (package:fvm/src/services/project_service.dart:42)
#10     ProjectService.findVersion (package:fvm/src/services/project_service.dart:68)
#11     ListCommand.run (package:fvm/src/commands/list_command.dart:48)
<asynchronous suspension>
#12     CommandRunner.runCommand (package:args/command_runner.dart:212)
<asynchronous suspension>
#13     FvmCommandRunner.runCommand (package:fvm/src/runner.dart:245)
<asynchronous suspension>
#14     FvmCommandRunner.run (package:fvm/src/runner.dart:124)
<asynchronous suspension>
#15     Scope.run (package:scope/src/scope.dart:151)
<asynchronous suspension>
#16     main (file:///private/tmp/fvm-20241202-89186-j6089r/fvm-3.2.1/bin/main.dart:13)
<asynchronous suspension>
```

</details>

**Desktop (please complete the following information):**

- OS: MacOS 15.1.1
- FVM Version 3.2.1
- ~~If Windows: Which Powershell are you using?~~

**Additional context**

There's no '.fvmrc' file in **project directory** and I hadn't run `fvm use version` in **project** though it only happens in **project directory**.

**Comment by petroczizoltan** [comment]
This happens because `VersionConstraint.parse` in the 'pub_semver' package is called with a `null` value.

**Comment by abs0** [comment]
We hit this with an app that had the following in pubspec.yaml:

```
isar_version: &isar_version 3.1.8
...
# isar_generator - Generate classes for using the Isar database
isar_generator:
  version: &isar_version
  hosted: https://pub.isar-community.dev/
```

I would say its fine for fvm to be stricter on pubspec.yaml than flutter... but this is quite a hard failure mode with very little clue to the developer. It would be nice if fvm could at least show a message of the form "likely bad version in pubspec.yaml", to help people resolve

**Comment by petroczizoltan** [comment]
Sure, let’s check what exception is thrown. If it’s something obvious, open a PR with a fix instead. :^)
